#!/bin/bash
read  -r -p "What is the max size wanted in kb? " maxSize
read  -r -p "What is the source folder? " sourceFolder

maxSize=$((maxSize/(42*57)))

echo "We can do files up to: "$maxSize

sourceFolder=FERG_DB_256
destinationFolder=$sourceFolder'_sample_'$maxSize
echo $destinationFolder
maxSize=$((maxSize+1))

rm -r -f $destinationFolder
mkdir $destinationFolder
cp $sourceFolder/README.txt $destinationFolder
for D in $sourceFolder/*; do 
	if [ -d $D ]; then
		name="$(basename $D)"
		
		subpath=$sourceFolder/$name
		
		#Make subpath folder HERE
		mkdir $destinationFolder/$name

		for S in $subpath/*; do
			subname="$(basename $S)"
			
			echo $subname

			#Make subfolder here
			mkdir $destinationFolder/$name/$subname
			
			folder=$sourceFolder/$name/$subname
			
			for f in $folder/*; do
				filename="$(basename $f)"

				#Create sub sub folder

				number=${filename//[^0-9]/}

				if [[ $number -lt $maxSize ]];
				then
					#Copy this file over
					from=$folder/$filename
					
					to=$destinationFolder/$name/$subname
					
					cp $from $to
				fi
			done
		done
	fi
done
